#!/bin/bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PYTHON_BIN="${PYTHON_BIN:-/home/lzh/miniconda3/envs/swarm-rl/bin/python}"

MODE="${1:-train}"
DEVICE="${DEVICE:-gpu}"
TRAIN_DIR="${TRAIN_DIR:-$ROOT_DIR/train_dir_velocity_nav}"
SOURCE_EXPERIMENT="${SOURCE_EXPERIMENT:-single_quad_velocity_nav_lidar_v5_safe_more_obst_balls_v14}"
SOURCE_CHECKPOINT_KIND="${SOURCE_CHECKPOINT_KIND:-best}"
EXPERIMENT="${EXPERIMENT:-single_quad_velocity_nav_lidar_v17_flexible_dense}"
NUM_WORKERS="${NUM_WORKERS:-4}"
NUM_ENVS_PER_WORKER="${NUM_ENVS_PER_WORKER:-4}"
TOTAL_STEPS="${TOTAL_STEPS:-30000000}"
LEARNING_RATE="${LEARNING_RATE:-0.000002}"
DEPTH_NOISE_STD="${DEPTH_NOISE_STD:-0.0}"
DEPTH_DROPOUT_PROB="${DEPTH_DROPOUT_PROB:-0.0}"
EPISODE_DURATION="${EPISODE_DURATION:-60.0}"
SIM_STEPS="${SIM_STEPS:-1}"
LIDAR_NUM_RAYS="${LIDAR_NUM_RAYS:-17}"
VELOCITY_XY_MAX="${VELOCITY_XY_MAX:-3.00}"
VELOCITY_Z_MAX="${VELOCITY_Z_MAX:-0.70}"
VELOCITY_MAX_ACC_XY="${VELOCITY_MAX_ACC_XY:-8.0}"
CONTROLLER_OBST_AVOID="${CONTROLLER_OBST_AVOID:-False}"
OBST_AVOID_DISTANCE="${OBST_AVOID_DISTANCE:-1.20}"
OBST_AVOID_MAX_SPEED="${OBST_AVOID_MAX_SPEED:-0.80}"
OBST_AVOID_GAIN="${OBST_AVOID_GAIN:-1.20}"
OBST_AVOID_PID_KP="${OBST_AVOID_PID_KP:-1.00}"
OBST_AVOID_PID_KI="${OBST_AVOID_PID_KI:-0.00}"
OBST_AVOID_PID_KD="${OBST_AVOID_PID_KD:-0.00}"
OBST_AVOID_PID_INTEGRAL_LIMIT="${OBST_AVOID_PID_INTEGRAL_LIMIT:-1.00}"
GOAL_BALL_CAPTURE_ASSIST="${GOAL_BALL_CAPTURE_ASSIST:-False}"
GOAL_BALL_CAPTURE_ASSIST_DISTANCE="${GOAL_BALL_CAPTURE_ASSIST_DISTANCE:-1.20}"
GOAL_BALL_CAPTURE_ASSIST_SPEED="${GOAL_BALL_CAPTURE_ASSIST_SPEED:-0.80}"
GOAL_BALL_TANGENT_DAMPING="${GOAL_BALL_TANGENT_DAMPING:-0.25}"
OBST_DENSITY="${OBST_DENSITY:-0.20}"
OBST_DENSITY_MIN="${OBST_DENSITY_MIN:-0.18}"
OBST_DENSITY_MAX="${OBST_DENSITY_MAX:-0.22}"
OBST_SIZE="${OBST_SIZE:-0.62}"
OBST_SIZE_MIN="${OBST_SIZE_MIN:-0.50}"
OBST_SIZE_MAX="${OBST_SIZE_MAX:-0.76}"
OBST_COLLISION_REWARD="${OBST_COLLISION_REWARD:-22.0}"
OBST_PROXIMITY_REWARD="${OBST_PROXIMITY_REWARD:-1.15}"
OBST_CLEARANCE_DELTA_REWARD="${OBST_CLEARANCE_DELTA_REWARD:-1.0}"
OBST_SAFE_DISTANCE="${OBST_SAFE_DISTANCE:-0.80}"
OBST_GUARD_DISTANCE="${OBST_GUARD_DISTANCE:-0.00}"
WALL_COLLISION_REWARD="${WALL_COLLISION_REWARD:-18.0}"
WALL_PROXIMITY_REWARD="${WALL_PROXIMITY_REWARD:-0.95}"
WALL_CLEARANCE_DELTA_REWARD="${WALL_CLEARANCE_DELTA_REWARD:-0.5}"
WALL_SAFE_DISTANCE="${WALL_SAFE_DISTANCE:-0.80}"
WALL_GUARD_DISTANCE="${WALL_GUARD_DISTANCE:-0.00}"
SAFE_FLIGHT_REWARD="${SAFE_FLIGHT_REWARD:-0.18}"
PATH_ALIGNMENT_REWARD="${PATH_ALIGNMENT_REWARD:-0.0}"
REWARD_SCALE="${REWARD_SCALE:-0.05}"
GOAL_BALL_VELOCITY_RESET="${GOAL_BALL_VELOCITY_RESET:-True}"
GOAL_BALL_VELOCITY_RESET_RATIO="${GOAL_BALL_VELOCITY_RESET_RATIO:-0.0}"
GOAL_BALL_RADIUS="${GOAL_BALL_RADIUS:-0.45}"
GOAL_BALL_COUNT="${GOAL_BALL_COUNT:-5}"
OBST_COLLISION_TERMINATE="${OBST_COLLISION_TERMINATE:-False}"
WALL_COLLISION_TERMINATE="${WALL_COLLISION_TERMINATE:-True}"
DOMAIN_RANDOM="${DOMAIN_RANDOM:-True}"
OBST_DENSITY_RANDOM="${OBST_DENSITY_RANDOM:-True}"
OBST_SIZE_RANDOM="${OBST_SIZE_RANDOM:-True}"

if [[ "$MODE" == "train" ]]; then
  echo "== Preparing 360-degree lidar warm start from $SOURCE_EXPERIMENT ($SOURCE_CHECKPOINT_KIND) =="
  "$PYTHON_BIN" -m swarm_rl.vision.prepare_depth_warmstart \
    --source_experiment="$SOURCE_EXPERIMENT" \
    --target_experiment="$EXPERIMENT" \
    --source_train_dir="$TRAIN_DIR" \
    --train_dir="$TRAIN_DIR" \
    --checkpoint_kind="$SOURCE_CHECKPOINT_KIND" \
    --target_action_dim=3 \
    --quads_control_mode=velocity \
    --quads_obstacle_obs_type=lidar \
    --quads_lidar_num_rays="$LIDAR_NUM_RAYS" \
    --reset_optimizer=True \
    --reset_training_progress=True \
    --checkpoint_lr="$LEARNING_RATE" \
    --quads_depth_noise_std="$DEPTH_NOISE_STD" \
    --quads_depth_dropout_prob="$DEPTH_DROPOUT_PROB" \
    --quads_velocity_xy_max="$VELOCITY_XY_MAX" \
    --quads_velocity_z_max="$VELOCITY_Z_MAX" \
    --quads_velocity_max_tilt_deg=32.0 \
    --quads_velocity_max_acc_xy="$VELOCITY_MAX_ACC_XY" \
    --quads_velocity_max_acc_z_up=2.2 \
    --quads_velocity_max_acc_z_down=2.2 \
    --quads_velocity_yaw_mode=keep \
    --quads_velocity_yaw_min_speed=0.2 \
    --quads_velocity_yaw_rate_max=0.0 \
    --quads_velocity_yaw_control_scale=0.6 \
    --quads_velocity_command_smoothing_tau=0.01 \
    --quads_controller_obstacle_avoidance="$CONTROLLER_OBST_AVOID" \
    --quads_obstacle_avoidance_distance="$OBST_AVOID_DISTANCE" \
    --quads_obstacle_avoidance_max_speed="$OBST_AVOID_MAX_SPEED" \
    --quads_obstacle_avoidance_gain="$OBST_AVOID_GAIN" \
    --quads_obstacle_avoidance_pid_kp="$OBST_AVOID_PID_KP" \
    --quads_obstacle_avoidance_pid_ki="$OBST_AVOID_PID_KI" \
    --quads_obstacle_avoidance_pid_kd="$OBST_AVOID_PID_KD" \
    --quads_obstacle_avoidance_pid_integral_limit="$OBST_AVOID_PID_INTEGRAL_LIMIT" \
    --quads_goal_ball_capture_assist="$GOAL_BALL_CAPTURE_ASSIST" \
    --quads_goal_ball_capture_assist_distance="$GOAL_BALL_CAPTURE_ASSIST_DISTANCE" \
    --quads_goal_ball_capture_assist_speed="$GOAL_BALL_CAPTURE_ASSIST_SPEED" \
    --quads_goal_ball_tangent_damping="$GOAL_BALL_TANGENT_DAMPING" \
    --quads_obst_density="$OBST_DENSITY" \
    --quads_obst_density_min="$OBST_DENSITY_MIN" \
    --quads_obst_density_max="$OBST_DENSITY_MAX" \
    --quads_obst_size="$OBST_SIZE" \
    --quads_obst_size_min="$OBST_SIZE_MIN" \
    --quads_obst_size_max="$OBST_SIZE_MAX" \
    --reward_scale="$REWARD_SCALE" \
    --quads_episode_duration="$EPISODE_DURATION" \
    --quads_sim_steps="$SIM_STEPS" \
    --quads_obst_collision_reward="$OBST_COLLISION_REWARD" \
    --quads_reward_obstacle_proximity="$OBST_PROXIMITY_REWARD" \
    --quads_reward_obstacle_clearance_delta="$OBST_CLEARANCE_DELTA_REWARD" \
    --quads_obstacle_safe_distance="$OBST_SAFE_DISTANCE" \
    --quads_obstacle_guard_distance="$OBST_GUARD_DISTANCE" \
    --quads_wall_collision_reward="$WALL_COLLISION_REWARD" \
    --quads_reward_wall_proximity="$WALL_PROXIMITY_REWARD" \
    --quads_reward_wall_clearance_delta="$WALL_CLEARANCE_DELTA_REWARD" \
    --quads_wall_safe_distance="$WALL_SAFE_DISTANCE" \
    --quads_wall_guard_distance="$WALL_GUARD_DISTANCE" \
    --quads_obst_collision_terminate="$OBST_COLLISION_TERMINATE" \
    --quads_wall_collision_terminate="$WALL_COLLISION_TERMINATE" \
    --quads_obstacle_guard_terminate=False \
    --quads_wall_guard_terminate=False \
    --quads_reward_progress=3.2 \
    --quads_reward_action_change=0.02 \
    --quads_reward_vertical_velocity=0.15 \
    --quads_reward_height_error=0.15 \
    --quads_reward_thrust=0.03 \
    --quads_reward_stagnation=0.10 \
    --quads_reward_safe_flight="$SAFE_FLIGHT_REWARD" \
    --quads_reward_path_alignment="$PATH_ALIGNMENT_REWARD" \
    --quads_goal_ball_reward=1.4 \
    --quads_goal_ball_radius="$GOAL_BALL_RADIUS" \
    --quads_goal_ball_count="$GOAL_BALL_COUNT" \
    --quads_goal_ball_velocity_reset="$GOAL_BALL_VELOCITY_RESET" \
    --quads_goal_ball_velocity_reset_ratio="$GOAL_BALL_VELOCITY_RESET_RATIO" \
    --force=True
  RESTART_BEHAVIOR="resume"
elif [[ "$MODE" == "resume" ]]; then
  RESTART_BEHAVIOR="resume"
elif [[ "$MODE" == "scratch" ]]; then
  RESTART_BEHAVIOR="overwrite"
else
  echo "Usage: $0 [train|resume|scratch]" >&2
  exit 1
fi

echo "== 360-degree lidar velocity obstacle-avoidance training =="

"$PYTHON_BIN" -m swarm_rl.train \
  --env=quadrotor_multi \
  --algo=APPO \
  --device="$DEVICE" \
  --experiment="$EXPERIMENT" \
  --train_dir="$TRAIN_DIR" \
  --restart_behavior="$RESTART_BEHAVIOR" \
  --load_checkpoint_kind=latest \
  --train_for_env_steps="$TOTAL_STEPS" \
  --use_rnn=False \
  --recurrence=1 \
  --num_workers="$NUM_WORKERS" \
  --num_envs_per_worker="$NUM_ENVS_PER_WORKER" \
  --learning_rate="$LEARNING_RATE" \
  --ppo_clip_value=5.0 \
  --nonlinearity=tanh \
  --actor_critic_share_weights=False \
  --policy_initialization=xavier_uniform \
  --adaptive_stddev=False \
  --with_vtrace=False \
  --max_policy_lag=100000000 \
  --rnn_size=128 \
  --gae_lambda=1.0 \
  --max_grad_norm=5.0 \
  --exploration_loss_coeff=0.0 \
  --rollout=128 \
  --batch_size=1024 \
  --with_pbt=False \
  --normalize_input=False \
  --normalize_returns=False \
  --reward_scale="$REWARD_SCALE" \
  --reward_clip=30 \
  --save_every_sec=240 \
  --keep_checkpoints=2 \
  --save_milestones_sec=100000000 \
  --replay_buffer_sample_prob=0.0 \
  --anneal_collision_steps=0 \
  --quads_use_numba=True \
  --quads_render=False \
  --quads_num_agents=1 \
  --quads_sim_steps="$SIM_STEPS" \
  --quads_control_mode=velocity \
  --quads_velocity_xy_max="$VELOCITY_XY_MAX" \
  --quads_velocity_z_max="$VELOCITY_Z_MAX" \
  --quads_velocity_max_tilt_deg=32.0 \
  --quads_velocity_max_acc_xy="$VELOCITY_MAX_ACC_XY" \
  --quads_velocity_max_acc_z_up=2.2 \
  --quads_velocity_max_acc_z_down=2.2 \
  --quads_velocity_yaw_mode=keep \
  --quads_velocity_yaw_min_speed=0.2 \
  --quads_velocity_yaw_rate_max=0.0 \
  --quads_velocity_yaw_control_scale=0.6 \
  --quads_velocity_command_smoothing_tau=0.01 \
  --quads_controller_obstacle_avoidance="$CONTROLLER_OBST_AVOID" \
  --quads_obstacle_avoidance_distance="$OBST_AVOID_DISTANCE" \
  --quads_obstacle_avoidance_max_speed="$OBST_AVOID_MAX_SPEED" \
  --quads_obstacle_avoidance_gain="$OBST_AVOID_GAIN" \
  --quads_obstacle_avoidance_pid_kp="$OBST_AVOID_PID_KP" \
  --quads_obstacle_avoidance_pid_ki="$OBST_AVOID_PID_KI" \
  --quads_obstacle_avoidance_pid_kd="$OBST_AVOID_PID_KD" \
  --quads_obstacle_avoidance_pid_integral_limit="$OBST_AVOID_PID_INTEGRAL_LIMIT" \
  --quads_goal_ball_capture_assist="$GOAL_BALL_CAPTURE_ASSIST" \
  --quads_goal_ball_capture_assist_distance="$GOAL_BALL_CAPTURE_ASSIST_DISTANCE" \
  --quads_goal_ball_capture_assist_speed="$GOAL_BALL_CAPTURE_ASSIST_SPEED" \
  --quads_goal_ball_tangent_damping="$GOAL_BALL_TANGENT_DAMPING" \
  --quads_episode_duration="$EPISODE_DURATION" \
  --quads_obs_repr=xyz_vxyz_R_omega_wall \
  --quads_neighbor_visible_num=0 \
  --quads_neighbor_obs_type=none \
  --quads_neighbor_encoder_type=no_encoder \
  --quads_neighbor_hidden_size=64 \
  --quads_obst_hidden_size=128 \
  --quads_collision_reward=0.0 \
  --quads_collision_hitbox_radius=2.0 \
  --quads_collision_falloff_radius=-1.0 \
  --quads_collision_smooth_max_penalty=0.0 \
  --quads_use_obstacles=True \
  --quads_obstacle_obs_type=lidar \
  --quads_depth_grid_width=3 \
  --quads_depth_grid_height=3 \
  --quads_lidar_num_rays="$LIDAR_NUM_RAYS" \
  --quads_depth_min_distance=0.05 \
  --quads_depth_max_distance=10.0 \
  --quads_depth_noise_std="$DEPTH_NOISE_STD" \
  --quads_depth_dropout_prob="$DEPTH_DROPOUT_PROB" \
  --quads_depth_normalize=False \
  --quads_obst_spawn_area 9 9 \
  --quads_room_dims 10 10 4 \
  --quads_goal_z_min=1.4 \
  --quads_goal_z_max=2.2 \
  --quads_camera_width=320 \
  --quads_camera_height=240 \
  --quads_camera_fov=145 \
  --quads_camera_pitch_deg=15 \
  --quads_use_downwash=False \
  --quads_mode=o_random \
  --quads_obst_density="$OBST_DENSITY" \
  --quads_obst_size="$OBST_SIZE" \
  --quads_obst_collision_reward="$OBST_COLLISION_REWARD" \
  --quads_reward_obstacle_proximity="$OBST_PROXIMITY_REWARD" \
  --quads_reward_obstacle_clearance_delta="$OBST_CLEARANCE_DELTA_REWARD" \
  --quads_obstacle_safe_distance="$OBST_SAFE_DISTANCE" \
  --quads_obstacle_guard_distance="$OBST_GUARD_DISTANCE" \
  --quads_obst_collision_terminate="$OBST_COLLISION_TERMINATE" \
  --quads_wall_collision_reward="$WALL_COLLISION_REWARD" \
  --quads_reward_wall_proximity="$WALL_PROXIMITY_REWARD" \
  --quads_reward_wall_clearance_delta="$WALL_CLEARANCE_DELTA_REWARD" \
  --quads_wall_safe_distance="$WALL_SAFE_DISTANCE" \
  --quads_wall_guard_distance="$WALL_GUARD_DISTANCE" \
  --quads_wall_collision_terminate="$WALL_COLLISION_TERMINATE" \
  --quads_obstacle_guard_terminate=False \
  --quads_wall_guard_terminate=False \
  --quads_domain_random="$DOMAIN_RANDOM" \
  --quads_obst_density_random="$OBST_DENSITY_RANDOM" \
  --quads_obst_density_min="$OBST_DENSITY_MIN" \
  --quads_obst_density_max="$OBST_DENSITY_MAX" \
  --quads_obst_size_random="$OBST_SIZE_RANDOM" \
  --quads_obst_size_min="$OBST_SIZE_MIN" \
  --quads_obst_size_max="$OBST_SIZE_MAX" \
  --quads_reward_progress=3.2 \
  --quads_reward_action_change=0.02 \
  --quads_reward_vertical_velocity=0.15 \
  --quads_reward_height_error=0.15 \
  --quads_reward_thrust=0.03 \
  --quads_reward_stagnation=0.10 \
  --quads_reward_safe_flight="$SAFE_FLIGHT_REWARD" \
  --quads_reward_path_alignment="$PATH_ALIGNMENT_REWARD" \
  --quads_use_goal_ball=True \
  --quads_goal_ball_reward=1.4 \
  --quads_goal_ball_radius="$GOAL_BALL_RADIUS" \
  --quads_goal_ball_count="$GOAL_BALL_COUNT" \
  --quads_goal_ball_velocity_reset="$GOAL_BALL_VELOCITY_RESET" \
  --quads_goal_ball_velocity_reset_ratio="$GOAL_BALL_VELOCITY_RESET_RATIO"
