#!/bin/bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODE="${1:-train}"

# A conservative long-run curriculum. Keep the world fixed and the learning
# signal small first, then increase density/randomization after the policy stops
# collapsing.
export SOURCE_EXPERIMENT="${SOURCE_EXPERIMENT:-single_quad_velocity_nav_lidar_v17_flexible_dense}"
export SOURCE_CHECKPOINT_KIND="${SOURCE_CHECKPOINT_KIND:-best}"
export EXPERIMENT="${EXPERIMENT:-single_quad_velocity_nav_lidar_v18_stable_long}"

export TOTAL_STEPS="${TOTAL_STEPS:-120000000}"
export LEARNING_RATE="${LEARNING_RATE:-0.000001}"
export REWARD_SCALE="${REWARD_SCALE:-0.03}"
export EPISODE_DURATION="${EPISODE_DURATION:-45.0}"

export VELOCITY_XY_MAX="${VELOCITY_XY_MAX:-2.20}"
export VELOCITY_Z_MAX="${VELOCITY_Z_MAX:-0.55}"
export VELOCITY_MAX_ACC_XY="${VELOCITY_MAX_ACC_XY:-5.8}"

export OBST_DENSITY="${OBST_DENSITY:-0.16}"
export OBST_DENSITY_MIN="${OBST_DENSITY_MIN:-0.16}"
export OBST_DENSITY_MAX="${OBST_DENSITY_MAX:-0.16}"
export OBST_SIZE="${OBST_SIZE:-0.62}"
export OBST_SIZE_MIN="${OBST_SIZE_MIN:-0.62}"
export OBST_SIZE_MAX="${OBST_SIZE_MAX:-0.62}"

export DOMAIN_RANDOM="${DOMAIN_RANDOM:-False}"
export OBST_DENSITY_RANDOM="${OBST_DENSITY_RANDOM:-False}"
export OBST_SIZE_RANDOM="${OBST_SIZE_RANDOM:-False}"

export OBST_COLLISION_TERMINATE="${OBST_COLLISION_TERMINATE:-True}"
export WALL_COLLISION_TERMINATE="${WALL_COLLISION_TERMINATE:-True}"
export OBST_COLLISION_REWARD="${OBST_COLLISION_REWARD:-18.0}"
export WALL_COLLISION_REWARD="${WALL_COLLISION_REWARD:-16.0}"

export OBST_PROXIMITY_REWARD="${OBST_PROXIMITY_REWARD:-0.85}"
export WALL_PROXIMITY_REWARD="${WALL_PROXIMITY_REWARD:-0.65}"
export OBST_CLEARANCE_DELTA_REWARD="${OBST_CLEARANCE_DELTA_REWARD:-0.25}"
export WALL_CLEARANCE_DELTA_REWARD="${WALL_CLEARANCE_DELTA_REWARD:-0.12}"
export OBST_SAFE_DISTANCE="${OBST_SAFE_DISTANCE:-0.85}"
export WALL_SAFE_DISTANCE="${WALL_SAFE_DISTANCE:-0.85}"
export SAFE_FLIGHT_REWARD="${SAFE_FLIGHT_REWARD:-0.22}"

export GOAL_BALL_COUNT="${GOAL_BALL_COUNT:-3}"
export GOAL_BALL_VELOCITY_RESET="${GOAL_BALL_VELOCITY_RESET:-True}"
export GOAL_BALL_VELOCITY_RESET_RATIO="${GOAL_BALL_VELOCITY_RESET_RATIO:-0.0}"

exec "$ROOT_DIR/train_local_velocity_depth_curriculum.sh" "$MODE"
