#!/bin/bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODE="${1:-train}"

# Formal long-run training. This starts from the v17 flexible policy and trains
# the harder task: denser obstacles, more balls, longer episodes, and mild
# obstacle randomization.
export SOURCE_EXPERIMENT="${SOURCE_EXPERIMENT:-single_quad_velocity_nav_lidar_v17_flexible_dense}"
export SOURCE_CHECKPOINT_KIND="${SOURCE_CHECKPOINT_KIND:-best}"
export EXPERIMENT="${EXPERIMENT:-single_quad_velocity_nav_lidar_v19_formal}"

export TOTAL_STEPS="${TOTAL_STEPS:-160000000}"
export LEARNING_RATE="${LEARNING_RATE:-0.000001}"
export REWARD_SCALE="${REWARD_SCALE:-0.03}"
export EPISODE_DURATION="${EPISODE_DURATION:-60.0}"

export VELOCITY_XY_MAX="${VELOCITY_XY_MAX:-2.60}"
export VELOCITY_Z_MAX="${VELOCITY_Z_MAX:-0.65}"
export VELOCITY_MAX_ACC_XY="${VELOCITY_MAX_ACC_XY:-6.5}"
export CONTROLLER_OBST_AVOID="${CONTROLLER_OBST_AVOID:-True}"
export OBST_AVOID_DISTANCE="${OBST_AVOID_DISTANCE:-1.55}"
export OBST_AVOID_MAX_SPEED="${OBST_AVOID_MAX_SPEED:-2.10}"
export OBST_AVOID_GAIN="${OBST_AVOID_GAIN:-1.00}"
export OBST_AVOID_PID_KP="${OBST_AVOID_PID_KP:-1.80}"
export OBST_AVOID_PID_KI="${OBST_AVOID_PID_KI:-0.20}"
export OBST_AVOID_PID_KD="${OBST_AVOID_PID_KD:-0.75}"
export OBST_AVOID_PID_INTEGRAL_LIMIT="${OBST_AVOID_PID_INTEGRAL_LIMIT:-0.80}"
export GOAL_BALL_CAPTURE_ASSIST="${GOAL_BALL_CAPTURE_ASSIST:-True}"
export GOAL_BALL_CAPTURE_ASSIST_DISTANCE="${GOAL_BALL_CAPTURE_ASSIST_DISTANCE:-1.15}"
export GOAL_BALL_CAPTURE_ASSIST_SPEED="${GOAL_BALL_CAPTURE_ASSIST_SPEED:-0.85}"
export GOAL_BALL_TANGENT_DAMPING="${GOAL_BALL_TANGENT_DAMPING:-0.45}"

export OBST_DENSITY="${OBST_DENSITY:-0.22}"
export OBST_DENSITY_MIN="${OBST_DENSITY_MIN:-0.20}"
export OBST_DENSITY_MAX="${OBST_DENSITY_MAX:-0.24}"
export OBST_SIZE="${OBST_SIZE:-0.62}"
export OBST_SIZE_MIN="${OBST_SIZE_MIN:-0.56}"
export OBST_SIZE_MAX="${OBST_SIZE_MAX:-0.70}"

export DOMAIN_RANDOM="${DOMAIN_RANDOM:-True}"
export OBST_DENSITY_RANDOM="${OBST_DENSITY_RANDOM:-True}"
export OBST_SIZE_RANDOM="${OBST_SIZE_RANDOM:-True}"

export OBST_COLLISION_TERMINATE="${OBST_COLLISION_TERMINATE:-True}"
export WALL_COLLISION_TERMINATE="${WALL_COLLISION_TERMINATE:-True}"
export OBST_COLLISION_REWARD="${OBST_COLLISION_REWARD:-22.0}"
export WALL_COLLISION_REWARD="${WALL_COLLISION_REWARD:-18.0}"

export OBST_PROXIMITY_REWARD="${OBST_PROXIMITY_REWARD:-1.05}"
export WALL_PROXIMITY_REWARD="${WALL_PROXIMITY_REWARD:-0.85}"
export OBST_CLEARANCE_DELTA_REWARD="${OBST_CLEARANCE_DELTA_REWARD:-0.35}"
export WALL_CLEARANCE_DELTA_REWARD="${WALL_CLEARANCE_DELTA_REWARD:-0.18}"
export OBST_SAFE_DISTANCE="${OBST_SAFE_DISTANCE:-0.85}"
export WALL_SAFE_DISTANCE="${WALL_SAFE_DISTANCE:-0.85}"
export SAFE_FLIGHT_REWARD="${SAFE_FLIGHT_REWARD:-0.20}"

export GOAL_BALL_COUNT="${GOAL_BALL_COUNT:-5}"
export GOAL_BALL_RADIUS="${GOAL_BALL_RADIUS:-0.65}"
export GOAL_BALL_VELOCITY_RESET="${GOAL_BALL_VELOCITY_RESET:-True}"
export GOAL_BALL_VELOCITY_RESET_RATIO="${GOAL_BALL_VELOCITY_RESET_RATIO:-0.0}"

exec "$ROOT_DIR/train_local_velocity_depth_curriculum.sh" "$MODE"
